# Nick Hance:
#   details: >
#     This is the description provided with each artist. Please ignore the image to the right, as it's just being used as a placeholder.
#   images:
#     - {thumb: "/tmp/palisade-10.jpg", full: "/tmp/bikes.jpg" }
#   url: { display: "reenhanced.com", href: "http://www.reenhanced.com"}
#   auction: http://ebay.com/

Example Artist:
  details: >
    <p>This is an example of the details section. You can add as many artists as you like.</p>
  images:
    - {thumb: "art/bikes-thumb/JESSUP1.jpg", full: "art/bikes/JESSUP1.jpg"}
    - {thumb: "art/bikes-thumb/JESSUP2.jpg", full: "art/bikes/JESSUP2.jpg"}
    - {thumb: "art/bikes-thumb/JESSUP3.jpg", full: "art/bikes/JESSUP3.jpg"}
  url: { display: "reenhanced.com", href: "http://reenhanced.com" }
  auction: http://www.reenhanced.com
